version: '3'
services: 
    database_ignite:
        image: 'postgres'
        restart: always
        environment:
            POSTGRES_PASSWORD: ignite
            POSTGRES_USER: docker
            POSTGRES_DB: rentx
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    app:
        container_name: rentx
        build: .
        ports:
            - "3333:3333"
        depends_on:
            - database_ignite